version: '3'

tasks:
  install: 
    cmds:
      - go mod tidy

  build:
    cmds:
      - go build -o bin/tss-lib-cli cmd/tss-lib-cli/main.go 

  run:
    cmds:
      - go run cmd/tss-lib-cli/main.go {{.CLI_ARGS}}

  fmt:
    cmds:
      - go fmt ./...

  clean:
    cmds:
      - rm -rf sig-*.json
      - rm -rf keygen-*.json
